// menu
export const GET_BADGE_MENU = 'GET_BADGE_MENU';
export const SET_BADGE_MENU = 'SET_BADGE_MENU';

export const FETCH_DATA_BY_SAGA = 'FETCH_DATA_BY_SAGA';
export const FETCH_DATA_BY_SAGA_ALERT_OK = 'FETCH_DATA_BY_SAGA_ALERT_OK';
export const FETCH_DATA_BY_SAGA_ALERT_FAIL = 'FETCH_DATA_BY_SAGA_ALERT_FAIL';
