// menu
export const GET_BADGE_MENU = 'GET_BADGE_MENU';
export const SET_BADGE_MENU = 'SET_BADGE_MENU';

// navigation
export const GET_NAVIGATION_HISTORY = 'GET_NAVIGATION_HISTORY';
export const SET_NAVIGATION_HISTORY = 'SET_NAVIGATION_HISTORY';
export const REMOVE_LAST_NAVIGATION_HISTORY = 'REMOVE_LAST_NAVIGATION_HISTORY';

export const FETCH_DATA_BY_SAGA = 'FETCH_DATA_BY_SAGA';
export const FETCH_DATA_BY_SAGA_ALERT_OK = 'FETCH_DATA_BY_SAGA_ALERT_OK';
export const FETCH_DATA_BY_SAGA_ALERT_FAIL = 'FETCH_DATA_BY_SAGA_ALERT_FAIL';
